"""cria setores e ramais

Revision ID: 7c41ba823b98
Revises: 
Create Date: 2026-09-16 15:45:48.909385

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7c41ba823b98'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('setores',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('nome', sa.String(length=200), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_setores')),
    sa.UniqueConstraint('nome', name=op.f('uq_setores_nome'))
    )
    op.create_table('ramais',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('numero', sa.String(length=20), nullable=False),
    sa.Column('setor_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['setor_id'], ['setores.id'], name=op.f('fk_ramais_setor_id_setores')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ramais'))
    )
    op.create_index(op.f('ix_ramais_setor_id'), 'ramais', ['setor_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ramais_setor_id'), table_name='ramais')
    op.drop_table('ramais')
    op.drop_table('setores')
    # ### end Alembic commands ###
